(package "php-runtime"
         "0.3.2"
         "Language binding bridge to PHP")

(website-url "https://github.com/emacs-php/php-runtime.el")
(keywords "processes" "php" "lisp")

(package-file "php-runtime.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "25.1")
(depends-on "compat")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
